
# Le parti del discorso

Le parole di una lingua vengono divise all'interno di categorie grammaticali. In italiano --una lingua flessiva come buona parte delle lingue indoeuropee [@graffiScalise2009]-- queste suddivisioni avvengono per criteri di natura sintattica, ovvero la posizione ed il ruolo delle parole all'interno della frase. Tradizionalmente possiamo riconoscere 9 diverse **parti del discorso** [@salvi2013], tra cui possiamo operare una ulteriore suddivisione: quelle (parti) *variabili* e quelle *invariabili*.  


## Le parti variabili

In italiano si definiscono parti **variabili** del discorso quelle che hanno la possibilità di modificarsi sulla base di alcuni *tratti* o *categorie grammaticali* [@simone1995 Cap.9] come il Genere, il Numero, la Persona, il Caso, il Tempo, l'Aspetto, il Modo ecc.. 

### Aggettivo  

L'aggettivo è un *modificatore* di altri elementi del discorso, soprattutto del sostantivo, con cui instaura un rapporto sintattico che si manifesta, nella maggior parte dei casi, nella concordanza grammaticale (*Brutto stamani il tempo e ancora più pestifero il Tempo* [@montale-satura], *Le lasagne scaldate nel micro che da solo mi sento cattivo* [@fibra2017]).


Tradizionalmente possiamo suddividere la classe di aggettivi in due categorie:

* Determinativi:
    * Possessivi (*mia, vostre, suo*)
    * Numerali:
        * Cardinali (*due, trentatré*) 
        * Ordinali (*primo, quarantatreesimo*)
    * Dimostrativi (*questo, quello*)
    * Indefiniti (*alcuni, tutti, nessuna*)
    * Interrogativi ed esclamativi (*quale?, quanti?, quale gioia!, ma che onore!*)
* Qualificativi (*forte, grande, bello, rettangolare, goloso, verde, vecchio*)

I determinativi esprimono alcune funzioni della referenza (per esempio il possesso), mentre i qualificativi esprimono dei caratteri quali il colore, la forma, l'aspetto, le qualità. Quella dei determinativi è una classe *chiusa*, mentre quella dei qualificativi è una classe *aperta* che prevede cioè la possibilità di espandersi in maniera indefinita.

### Articolo

L'articolo è quella particella che si accompagna al nome o ad altre parti del discorso in funzione sostantivata. In italiano esso concorda nei tratti di Numero, Persona, Genere con il sostantivo di riferimento [@grandi2010].
Le lingue del mondo non presentano tutte lo stesso comportamento nei riguardi della posizione e/o della presenza dell'articolo e possiamo trovare:

* Lingue senza articoli (*ceco, slovacco*)
* Lingue con articoli
    * Proclitici (*italiano, inglese*)
    * Enclitici (*bulgaro, macedone*)

In una lingua come l'italiano, la presenza dell'articolo è lo *standard*, ovvero non ha una funzione specifica mentre la sua assenza assume significato. Così, per esempio, in **italiano standard**^[Alcune varietà di italiano, quali i dialetti settentrionali, hanno invece gli articoli in questi contesti [@loporcaro2009].] i nomi propri escludono l'articolo (*Marta va in città* vs. *\*La Marta va in città*) così come è esclusa la possibilità di trovare l'articolo in combinazione con il possessivo nei nomi di famiglia (*mio figlio si chiama Luigi* vs. *\* Il mio figlio si chiama Luigi*). 

\begin{table}[]
\begin{tabular}{@{}lrrrrrr@{}}
\toprule
      & \multicolumn{2}{c}{Definito} & \multicolumn{2}{c}{Indefinito} & \multicolumn{2}{c}{Partitivo} \\ \midrule
      & Sing          & Plur         & Sing           & Plur          & Sing          & Plur          \\
Masch & il            & i            & un             & -             & del           & dei           \\
Masch & lo            & gli          & uno            & -             & dello         & degli         \\
Fem   & la            & le           & una            & -             & della         & delle         \\ \bottomrule
\end{tabular}
\caption{Tabella riassuntiva degli articoli in italiano}
\end{table}





#### Definito

L'articolo definito o *determinativo* può indicare un referente determinato, ovvero noto (*Sto cercando il libro*, *hai visto la mia maglietta?*).


#### Indefinito

Quello indefinito o indeterminativo può essere usato per indicare un sostantivo indefinito specifico (*non trovo un libro che avevo lasciato a casa*) oppure non specifico (*per la nuova casa vorrei trovare un inquilino simpatico*). Gli articoli indefiniti non possono essere usati al plurale e la loro forma è la stessa del numero "uno" (1). 


#### Partitivo

L'articolo partitivo si usa per indicare quantità indefinite o parti di un insieme (*vorrei del pane*, *sto cercando dei libri*, *la maggior parte dei ragazzi pensa solo a una cosa*). Si forma dall'unione delle forme "di" con l'articolo definito (*del*, *dello*, *della*, *dei*, *degli*, *delle*).

### Nome

Il nome o *sostantivo* è la parte del discorso che designa entità, persone, oggetti, idee, fatti ecc. 
Il nome è una parte variabile, che modifica la sua flessione (*morfologia flessionale*) in conseguenza di alcuni tratti della parola quale il Numero, il Genere e che può modificarsi tramite l'aggiunta di morfemi che ne codificano un significato diminutivo, vezzeggiativo ecc. (*morfologia derivazionale*).

Dal punto di vista formale possiamo dividere il nome in base ad alcune categorie grammaticali:

* Genere
    * Maschile 
    * Femminile 
    * Genere comune
    * Genere misto (*osso/ossa, uovo/uova*)

* Numero
    * Singolare
    * Plurale 
    * Collettivo (*gregge, biblioteca*)


In italiano la marca di numero e di genere è resa in un unico suffisso *portmanteu* (cioè che testimonia diversi valori insieme), mentre in lingue agglutinanti di solito questi tratti possono essere realizzati da differenti morfemi. 


### Pronome

Il pronome è quella categoria grammaticale *coreferenziale* del nome a cui si riferisce e sostituisce: presenta cioè lo stesso riferimento --quale può essere la persona-- (*referenza*) del sostantivo (*Ho visto Gianni. Sì, lui*(=Gianni) *sta molto bene*; *La sigaretta, Luigi la*(=sigaretta) *fuma dopo il caffè*).

I pronomi sono **personali** (*io, tu, noi*), **possessivi** (*mio, tua*), **dimostrativi** (*questo, quello*), **riflessivi** (*io mi pettino, voi vi amate?*), **relativi** (*che, la quale*), **interrogativi** (*non so chi tu sia*), **numerali**.

La differenza tra pronome e aggettivo in alcuni casi è esclusivamente riferibile al contesto sintattico, come dimostra l'esempio seguente:


(@)
    \gll    La              mia             penna       è           blu,    la      tua             è       nera.  
            ART.DEF.F.sg    ADJ.POSS.F.1sg  NOUN.F.sg   COPULA.3sg  ADJ.    ART.    PRON.POSS.F.2sg COPULA.3sg  ADJ.  
    \glt    ''


L'italiano è una lingua a soggetto nullo, che permette cioè la possibilità di omettere il pronome personale in alcune costruzioni (*(Io) mangio il pane con la marmellata*).


### Verbo

Il verbo è la parte del discorso che codifica gli stati, gli eventi, le azioni ecc. 
Possiamo distinguere in esso alcuni caratteri formali quali la classe di coniugazione (*-are, -ere, -ire*), i tratti (aspetto, modo ecc.), il numero di argomenti (verbi transitivi, intransitivi ecc.).

#### Categorie del verbo

Sono categorie del verbo il Tempo, l'Aspetto e il Modo (TAM).

L'italiano è una lingua 


#### Argomenti del verbo

Negli studi moderni la transitività è trattata piuttosto come un *continuum* con degli estremi che corrispondono grosso modo al numero di argomenti del verbo. 
Possiamo distinguere i verbi sulla base del numero di argomenti di cui necessitano:

* Intransitivi
    * Inergativi
    * Inaccusativi
* Transitivi
* Ditransitivi
 

##### Intransitivi

I verbi intransitivi o mono-argomentali presentano un solo argomento (*Lui cammina*, *Lei corre*) e sono divisi in due sotto-categorie. Nei verbi **inergativi** (dal greco ant.  ἔργον *érgon*, "lavoro")  il soggetto ha le proprietà sintattiche tipiche di un soggetto transitivo, mentre in quelli **inaccusativi** il soggetto si comporta più come un oggetto delle costruzioni transitive. Sono esempio della prima sottocategoria verbi quali *correre, lavorare, ridere*, mentre della seconda *scoppiare, sparire, cadere*. Un modo per distinguere tali classi di verbi gli uni dagli altri è verificare l'ausiliare nei tempi composti: quelli inergativi presentano il verbo *avere* (*ieri ho lavorato molto*), gli inaccusativi hanno *essere* (*dov'eri? sei sparito subito!*) e l'accordo del participio passato nei tratti del Numero, possibile con gli inaccusativi e non con gli inergativi: *avete lavorato duramente* vs. *siete spariti subito!*. L'argomento dei verbi intransitivi è il soggetto (S).

##### Transitivi

I verbi transitivi collegano prototipicamente due argomenti: il soggetto transitivo (A) e l'oggetto diretto (O) (*Mario mangia la mela*, *Gli attori recitano una commedia*). 

Le costruzioni transitive possono essere regolarmente trasformate in corrispondenti frasi *passive*: in questo caso l'oggetto viene posto in posizione di soggetto e il soggetto transitivo in agente:

(@)
    \gll    Mario   mangia  la mela.  
            A       VP      O  
    \glt  


(@)
    \gll    La mela     è mangiata  da Mario.  
            S           VP          Ag  
    \glt  

Così, spesso, le costruzioni transitive possono essere trasformate in corrispondenti intransitive (con una certa modifica nel carico semantico dell'enunciato):

(@)
    \gll    Mario   mangia.  
            S       VP        
    \glt  



##### Ditransitivi e oltre

I verbi di-transitivi reggono 3 argomenti: A,O e Oggetto Indiretto (IO), e possono essere passivizzati:

(@)
    \gll    Mario   regala  una rosa    a Luigi.  
            A       VP      O           IO        
    \glt  


(@)
    \gll    Una rosa    è regalata  a Luigi da Mario.  
            S           VP          IO      IO        
    \glt  

Per esemplificare un verbo tetravalente, ovvero che regge 4 argomenti, possiamo riferirci a *tradurre*:

(@)
    \gll    San Girolamo    tradusse    alcuni libri della Bibbia   dal greco   al latino.  
            A               VP          O                           IO          IO        
    \glt 




## Le parti invariabili

Sono parti invariabili del discorso quelle che si presentano sempre nella stessa forma, senza cambiamenti morfologici.

### Avverbio

L'avverbio è un modificatore di altri elementi della frase come: aggettivi (*Gli spaghetti sono molto buoni*), verbi (*Sappiamo cucinare bene gli spaghetti*), ed altri avverbi (*Arriveremo molto presto*).
Un'espressione formata da diverse parole con funzione di avverbio è detta *locuzione avverbiale*.

Gli avverbi possono essere di **modo**--indicano cioè il modo dell'azione (*velocemente, bene*)--, di **tempo** (*ora, mai, sempre*), di **luogo** (*qui, lì, giù*), di **quantità** (*poco, molto*), **di opinione** (*sì, no, esatto, chissà, magari*), **interrogativi ed esclamativi** (*come, perché, dove, quando*), **presentativi** (*inoltre, ecco*).

Gli avverbi hanno gli stessi *gradi* dell'aggettivo e in certi casi possono essere alterati da suffissi:

* Gradi
    * Positivo (*velocemente*)
    * Comparativo
        * Di maggioranza (*più velocemente*)
        * Di minoranza (*meno velocemente*)
        * Di uguaglianza (*tanto velocemente quanto*)
    * Superlativo
        * Relativo (*il più velocemente (possibile)*)
        * Assoluto (*velocissimamente*)

* Alterazioni
    * Diminutivo 
    * Vezzeggiativo
    * Accrescitivo
    * Dispregiativo

### Congiunzione

La congiunzione è la parte del discorso che permette l'unione di sintagmi o frasi. Possono essere **positive** (*e, anche, pure*), **negative** (*né, neanche, nemmeno*), **disgiuntive** (*o, oppure, altrimenti*), **avversative** (*anzi, ma, tuttavia, nonostante*), **conclusive** (*dunque, allorché*).


### Interiezione

L'interiezione esprime un particolare atteggiamento del parlante. Sono esempi di interiezioni **proprie** particelle quali *ah!, eh!, oh!*, **improprie** se comprendono altre parti del discorso (*zitto!, cavolo!*) e **locuzioni interiettive** se formate da più parole (*per Dio!, per amor del cielo, porca miseria*).
Particolarmente usata nella comunicazione orale, presenta una grande varianza all'interno dei sistemi dialettali, dando luogo a espressioni particolarmente colorite(*figa, pota, cazzo, stocazzo, sticazzi, minchia, mecojoni*).

### Preposizione

Le preposizioni sono poste *prima* del nome o di altri elementi (*Sono andato a Praga la settimana scorsa; Non ho mai lavorato in Germania; Vieni prima di subito*). 

Sono preposizioni **proprie** *di, a, da, in, con, su, per, tra,fra*, **improprie** *dopo, tranne, salvo, verso, contro, circa*, **locuzioni prepositive** *a causa di, per mezzo di, in base a*.


## I tratti


A questo punto possiamo trasporre alcune di queste definizioni grammaticali all'interno di una prospettiva sintattica. La prima domanda a cui possiamo tentare di dare una risposta è: *cos'è una parola? E in che modo le parole si organizzano in una grammatica?*
Abbiamo visto infatti che le parti del discorso sono delle categorie di parole unite tra loro dal fatto che possiamo sostituire una parola da una della stessa categoria (*Il libro è sul tavolo* / *Un libro è sul tavolo*), senza cambiarne lo statuto sintattico.

Rimane dunque la definizione di *parola*. Possiamo, dal punto di vista sintattico definire le parole come elementi linguistici che presentano dei *tratti*. Ad es. nel caso dei nomi, i tratti possono essere il Genere, il Numero, il Caso. Questa definizione, che non presenta complessità di natura teoretica, trova spazio in un'analisi esclusivamente sintattica e ci permette di pensare alle parole come a degli oggetti dotati di certe proprietà (i tratti). In italiano possiamo distinguere varie categorie sulla base dei tratti che presentano:

| Categoria          | Tratti                                |
|--------------------|---------------------------------------|
| Nome (N)           | Numero, Genere, Caso                  |
| Aggettivo (A)      | Numero, Genere                        |
| Determinante (D)   | Numero, Genere, Caso                  |
| (Pronome)          | Numero, Genere, Caso, Persona         |
| Quantificatore (Q) | Numero, Genere                        |
| Verbo (V)          | Numero, Persona, Tempo, Modo, Aspetto |


Così, le parole sono le unità concrete della lingua, e la sintassi è quella componente che assembla le varie parti del discorso sulla base di entità più *piccole* della parola, i *tratti*.