# La frase complessa

Tutta questa dispensa si focalizza sulla frase complessa. 

Possiamo definire la frase complessa come quella formata dall'unione di più frasi attraverso diverse strategie sintattiche e che permette una certa gerarchia delle varie frasi.

## Coordinazione, giustapposizione, subordinazione

Se fino a questo momento ci siamo concentrati sulla frase semplice --quella che presenta un predicato verbale e i suoi argomenti-- ora possiamo cominciare ad affrontare il vero nucleo del discorso: la frase complessa ed i modi attraverso cui possiamo unire più frasi tra loro.


Due frasi possono essere unite attraverso una **coordinazione** (*paratassi*) se si trovano allo stesso livello --vale a dire che possono risultare come frasi a sé:

(@)
    Luigi insegna geologia e Maria è una cantante.

Possiamo distinguere diversi tipi di **congiunzioni coordinanti** che mettono in relazione due elementi, basandoci sulla *qualità* di tale coordinazione:

*   **avversative**: opposizione  
    *Volevo andare in cajovna* ma *è chiusa*
*   **disgiuntive**: alternativa  
    *Preferisci il caffè* o *una tisana?*
*   **esplicative**: riformulazione di qualcosa già detto  
    *Il costituente di tempo finito è TP,* ovvero *Tense Phrase*
*   **conclusive**: introducono l'effetto di una causa o di un motivo  
    *Il pivovar era chiuso* quindi *siamo andati a ballare*

Le congiunzioni possono a loro volta combinarsi tra loro quando c'è una certa continuità nel rapporto di coordinazione. Così per es. *e ma* risulta quasi incomprensibile per un parlante nativo, mentre *e invece, ma invece, e quindi, ma però* risultano comprensibili anche se possono essere condannate dalla norma linguistica e quindi inadatte a registri alti della lingua (è il caso p.es. di *ma però*, estremamente colloquiale).


Non necessariamente le frasi coordinate sono frasi principali, ma possiamo avere una coordinazione tra strutture di livello secondario ecc:

(@)
    Hanno sicuramente molti soldi perché Luigi insegna geologia e Maria è una cantante.

Così, "*Hanno sicuramente molti soldi*" è la frase **principale**, mentre "*perché L.insegna*" è una **subordinata** della principale e "*e Maria è una cantante*" è la **coordinata** della subordinata.

Così, ogni subordinata ha una frase reggente, la quale può essere a sua volta una principale o una subordinata, come in:

(@)
    Hanno sicuramente molti soldi perché hanno comprato una casa che hanno pagato moltissimo.

Qui la frase "*che hanno pagato moltissimo*" continua il discorso della frase reggente "*hanno comprato una casa*". 
Così la frase reggente non è per forza una principale e in questo esempio abbiamo una principale, una subordinata di 1° grado e una di 2°.

In maniera simile, le costruzioni paratattiche possono essere unite per **giustapposizione**. In questo caso non vi saranno elementi lessicali ad unirle, bensì segni di punteggiatura:

(@)
    Piove. Fa freddo. 

Bisogna aggiungere che negli studi sintattici il fenomeno della coordinazione è particolarmente dibattuto e presenta diversi approcci per la sua spiegazione. Ai fini di questa dispensa sarà forse utile utilizzare una notazione che presenti un costituente dato dalla testa della congiunzione e i 2 elementi in posizione l'uno di Specificatore, l'altro di Complementatore, che chiameremo con il simbolo della E-commerciale "&":

```{r treeCongiunzione, echo=FALSE, engine='tikz', out.width='70%', fig.ext=if (knitr:::is_latex_output()) 'pdf' else 'svg', fig.cap='Il costituente di congiunzione', engine.opts = list(template = "latex/tikz2pdf.tex"), fig.align='center'}
\begin{tikzpicture}
\tikzset{every tree node/.style={align=center,anchor=north}}
\Tree 
[ .\&P 
[ .CP \edge[roof]; {La cajovna era chiusa} ]
[  [ .\& [ .e ] ]
[ .CP \edge[roof]; {siamo andati al pivovar} ]
]
]

\end{tikzpicture}
```

## La frase principale

All'interno della frase complessa, la *proposizione principale* è quella di *rango* più alto, ovvero quella da cui dipendono in maniera diretta o indiretta le subordinate del periodo:

(@)
    Non siamo andati in cajovna [perché era chiusa].

Se l'esempio precedente ci mostra una frase semplice sintatticamente autonoma, che ha *saturato* il suo nucleo sintattico, (*non siamo andati in cajovna*) come proposizione principale, non sempre la principale gode di tale autonomia, dove presenta come argomento una proposizione, ovvero il suo nucleo sintattico non è saturo ma necessita di un'altra frase:

(@)
    Credo che non andremo in cajovna
 
In maniera identica tale distinzione può essere fatta per proposizioni secondarie che reggono a loro volta delle subordinate:

(@)
    a.  Credo [che non andremo in cajovna [perché è chiusa]]
    a.  Credo [che stasera non sappiamo [dove andremo]]

## La frase subordinata

Così come abbiamo fatto riferimento agli *argomenti* della frase semplice, così possiamo riferirci anche alla sintassi della frase complessa, dividendo queste frasi complesse all'interno di categorie che specificano il ruolo argomentale rispetto al *nucleo* della principale. Così una prima distinzione può essere operata tra:

*   **Proposizioni argomentali**  
    Le proposizioni fanno parte del nucleo della reggente
*   **Non argomentali**  
    Così come i circostanziali, non contribuiscono al nucleo principale ma sono legate alla reggente da relazioni logico-semantiche (tempo, concessione ecc.)
*   **Relative**  
    Modificano un sintagma nominale della reggente 

A queste possiamo unire un'altra distinzione tra le proposizioni **esplicite** --che contengono un verbo di modo finito-- e **implicite** con un verbo di modo indefinito.

Le prossime sezioni della dispensa si focalizzeranno sulla spiegazione dei diversi tipi di proposizione.
