# Proposizioni non argomentali

Se come abbiamo mostrato finora le subordinate possono essere utilizzate in funzione di argomenti sintattici della reggente --sia come soggetto che come oggetto diretto e indiretto-- un'importante categoria delle subordinate è rappresentata da quelle proposizioni che non hanno valore argomentale. Così queste frasi si presentano come dei *circostanziali*, che presentano ognuno un tipico modo di codificare il rapporto delle informazioni tra reggente e secondarie, instaurando ora un rapporto di dipendenza e causalità, ora uno di negazione, comparazione, e così via. 

Come già visto per le argomentali, rimane tipica di tutte le subordinate la possibilità di essere resa in maniera *esplicita* --con un verbo di modo finito-- o *implicita*. Anche qui, come già visto nelle argomentali, potrebbero esserci delle differenze tra le forme delle preposizioni nel modo in cui possono accettare tale variazione e sulle preposizioni e i costrutti utilizzati. Vedremo nel dettaglio la maggior parte delle subordinate non argomentali qui di seguito. Spesso è possibile trovare nei manuali la dicitura di proposizioni *avverbiali* per riferirci a questo tipo di subordinazione: avverbiali e non argomentali valgono sostanzialmente per significare la stessa cosa ma qui si preferisce la distinzione tra argomento/non argomento per esplicitare la loro funzione nei riguardi del nucleo sintattico della reggente.

Sebbene ciascuna di queste classi di subordinate sia introdotta da un certo numero di elementi lessicali tipici, spesso alcune subordinate usano tali elementi in maniera non strettamente aderente al significato originario.

## Avversative

Le subordinate avversative esplicite si avvalgono di introduttori lessicali mutuati da quelle temporali (*mentre, quando*) e relativo (*laddove*), ma codificano un rapporto di contrapposizione tra l'evento della reggente e quello dell'avversativa:

(@) Luigi non lavora, mentre Mario è avvocato

A volte è possibile trovare *invece* usato come rafforzativo (*Luigi non lavora,* mentre invece *Mario è avvocato*). Vi è di solito una pausa intonativa tra le due frasi.

Non sempre risulta chiarissimo distinguere tra un uso perfettamente temporale ed uno avversativo, e su tale ambiguità può operare una scelta stilistica da parte di un autore:

(@) Promettevo di portarti via / Quando l'auto nemmeno partiva [@fibra2017]

In questi casi si può dire che se invertiamo l'ordine delle frasi la lettura sarà probabilmente temporale, mentre nel costrutto avversativo la subordinata segue la reggente [@bianco2017, 95].

Le avversative implicite si avvalgono di introduttori quali *anziché, piuttosto che* ecc. e il verbo all'infinito:

(@) 
    a.  Piuttosto che sposarmi, preferisco farmi prete
    a.  Anziché studiare per il test, gli studenti hanno preferito andare al lago

## Causali

La funzione di queste frasi è instaurare un rapporto causale con l'evento della reggente, esplicitandone la causa o il motivo per cui quest'ultimo si verifica. 

Le causali esplicite sono introdotte da diverse congiunzioni (*perché, poiché, siccome* ecc.) e locuzioni (*dal momento che, date che, visto che*, ecc.): 

(@)
    a. Lo perdonavo [perché mi faceva ridere] (N. Frassica, in *Il Fatto Quotidiano*, 18/03/2019)
    a. Mi sono innamorato di te [perché non avevo niente da fare] (L. Tenco)
    a. lo fanno per salvare le poltrone [visto che l'80% di loro se va a casa] (M. Renzi, in *Repubblica*, 18/02/2019)

Certi introduttori impongono al costrutto un certo ordine di precedenza. Così, con *perché* la subordinata non può precedere la reggente, mentre con *siccome* --al contrario-- essa la precede:

(@)
    a. [Siccome la politica non ci è riuscita], si sperava che fosse il Politecnico a risolvere il rebus di piazza Baldissera (S. Parola, in *Repubblica*, 07/03/2019)
    a. La Tav si farà [perché il vero capo del governo si chiama Matteo Salvini] (N. Zingaretti, in *Repubblica*, 10/03/2019)

Quando i soggetti delle frasi sono *coreferenti* --si riferiscono, cioè allo stesso SN-- possiamo avere la forma implicita:

(@) **Per + Infinito**  
    a. L'imputato è stato assolto per non aver commesso il fatto
    a. i tuoi occhi assunti da tre anni/ i tuoi occhi per loro,/ ormai buoni per setacciare spiagge con la scusa del corallo/ o per buttarsi in un cinema con una pietra al collo/ e troppo stanchi per non vergognarsi/ di confessarlo nei miei (F. De André, *Quando verranno a chiederti del nostro amore*)

(@) **Participio passato**  
    a. Uccise la compagna, ottiene le attenuanti perché disperato (M. Giannini, in *Repubblica*, 13/03/2019)
    a. Poiché infortunato, è stato costretto ad abbandonare il campo

(@) **Gerundio**  
    a. Avendo studiato da tempo la piazza [...], mi era sembrato doveroso [...] dare una possibile soluzione (A. Capasso, in *Repubblica*, 15/02/2019)
    a. Avendo studiato a Firenze, ho sempre mantenuto riserve su marketing territoriale e turismo (F. Bellomo, in *Repubblica*, 05/05/2018) 

Spesso un rapporto di causazione (causa o motivo) presuppone un certo grado di successione temporale tra gli eventi descritti, e questo potrebbe spiegare il motivo per cui alcuni introduttori dal valore originario temporale abbiano esteso il loro uso in questi contesti (*dal momento che, quando*, ecc.).



## Comparative

Queste subordinate esprimono una comparazione di *uguaglianza* o *disuguaglianza* rispetto a un costituente della reggente, dove il costituente della reggente è detto "primo termine di paragone" e la subordinata è il "secondo termine di paragone". Il secondo termine di paragone può presentare una negazione pleonastica --che non cambia il significato della frase-- esclusivamente nelle comparazioni di disuguaglianza:

(@)
    a. Salvini è più fragile di quanto non dicano i sondaggi (in *L'Espresso*, 08/03/2019)
    a. Ma il caudillo sembra meno forte di quel che proclama (A. Lombardi, in *Repubblica*, 28/01/2019)
    a. Per alcune specie, tutelare gli individui che fungono da 'archivi' di conoscenza sociale risulta importante tanto quanto lo è tutelare l'habitat critico di cui necessita la specie, come per esempio nei gruppi matriarcali degli elefanti (in *Repubblica*, 12/03/2019)

Nella forma implicita presentano il verbo all'infinito:

(@) Mi piace più mangiare che cucinare


## Concessive

Il rapporto di concessione si instaura tra una causa che non impedisce lo svolgimento dell'evento (causa *frustrata*):

(@) L'utile non è il fine della poesia, benché questa possa giovare (G. Leopardi, *Zibaldone*)

La subordinata concessiva utilizza un certo numero di introduttori e può presentarsi in diverse costruzioni:

* congiunzioni (*benché, malgrado, nonostante ecc.*) e locuzioni (*per quanto ecc.*) con il congiuntivo

* locuzioni (*con tutto che*) e avverbi (*neanche, nemmeno, neppure, pure*) e dalla congiunzione *se* con l'indicativo

* pronomi e aggettivi indefiniti [o avverbi] (*checché, qualsiasi, comunque, dovunque*) con il congiuntivo

* dalla costruzione *per+AGG+che+essere* con congiuntivo

Le concessive implicite sono possibili quando il soggetto delle due proposizioni è coreferenziale:

(@)
    a. Pur ballando (Luisa)/*Mario male, Luisa è andata alla festa
    a. Per essere italiano, parla bene l'inglese

Si può procedere a trasformare la concessiva in avversativa, mentre non è sempre possibile il contrario:

(@)
    a. Mario fuma benché faccia male 
    a. Mario fuma, mentre fumare fa male


## Condizionali

La proposizione condizionale è una subordinata, introdotta nella maggior parte dei casi dall'operatore "se", che esplicita la *condizione* da cui dipende l'avverarsi dell'evento descritto nella proposizione reggente. L'insieme costituito dalla reggente (*apodosi*) e dalla subordinata (*protasi*) è detto *periodo ipotetico*. Prese singolarmente, la protasi e l'apodosi possono essere frasi semplici o a loro volta complesse:

(@) 
    a. Ma se io avessi previsto tutto questo [...] forse farei lo stesso (F. Guccini, *L'avvelenata*, 1976)
    a. Se il treno non è in ritardo e i vagoni non sono troppo affollati, faremo un viaggio comodo e arriveremo in tempo per la partita 

Non è necessario che l'apodosi sia la proposizione principale, ma può essere a sua volta una subordinata della principale, tale che la protasi sia subordinata della subordinata:

(@) Mi hanno detto che dovrò studiare bene, se voglio passare l'esame

Con la protasi si ipotizza una condizione che, soddisfatta, permette il verificarsi di quanto espresso nell'apodosi.

Possiamo distinguere 4 tipi di periodo ipotetico con la subordinata esplicita, in considerazione dei modi verbali di protasi e apodosi e del tipo di fatto descritto:

(@) 
    **Della realtà**  
    Quando il fatto descritto nella protasi è un evento molto probabile o reale  
    *Se una cosa mi piace, la compro* 

(@) 
    **Della possibilità**  
    Quando il fatto è probabile ma non certo    
    *Se mi chiedesse di tornare da lei, lo farei*

(@) 
    **Dell'irrealtà (presente)**  
    Descrive una ipotesi irrealizzabile, nel presente    
    *Se fossi al posto tuo, lo comprerei*

(@) 
    **Dell'irrealtà (passato)**  
    Ipotesi irrealizzabile, nel passato  
    *Se fossi stato al tuo posto, l'avrei comprato*


| **Tipo**                 | **Protasi**            | **Apodosi**                        |
|--------------------------|------------------------|------------------------------------|
| Della realtà             | Indicativo             | Indicativo / Imperativo            |
| Della possibilità        | Congiuntivo imperfetto | Condizionale presente / Imperativo |
| Dell'irrealtà (presente) | Congiuntivo imperfetto | Condizionale presente              |
| Dell'irrealtà (passato)  | Congiuntivo trapassato | Condizionale passato               |

: Tabella del periodo ipotetico  

La proposizione condizionale implicita può essere:

*   all'infinito, introdotta da "a"  
    *A pensarci bene, questa separazione è la soluzione migliore*
*   al participio passato, a volte introdotta da "se"  
    *(Se) accompagnato da un buon vino, il cibo è migliore
*   al gerundio  
    *Volendo, potremmo comunque andare alla festa*

**Costruzioni bi-negative**

Sono costruzioni in cui l'apodosi presenta un contenuto falso e una concordanza generalmente all'indicativo:

(@) Se tu giochi bene a calcio, io sono Leonardo Da Vinci

Un costrutto simile è quello con apodosi all'imperativo --se non si verifica quanto richiesto nella protasi, allora l'apodosi risulta falsa:

(@) Se sei (davvero) un bravo cuoco, prepara tu la cena stasera 

**Costruzioni bi-affermative**

Qui invece il contenuto dell'apodosi e/o della protasi è un fatto comunemente ritenuto come vero. Così il costrutto presenta la concordanza all'indicativo:

(@) 
    a. Se la situazione economica è disastrosa, quella culturale non è migliore
    a. Se Atene piange, Sparta non ride




## Consecutive

A differenza del costrutto causale, in quello consecutivo la reggente contiene la causa/motivo, mentre la subordinata consecutiva la conseguenza o il risultato scaturito dall'evento della reggente:

(@) 
    a. Ho studiato così tanto che mi si incrociano gli occhi
    a. Ero davvero stanco, sicché me ne sono andato a dormire

Le costruzioni consecutive presentano un certo ordine tra le sue costituenti, per cui l'evento della reggente precede sempre la subordinata:

(@) (*) Che mi si incrociano gli occhi, ho studiato così tanto

Nella maggior parte dei casi, la consecutiva è introdotta da "che" se di modo finito e "da" se implicita:

(@)
    a. Piove tanto da far paura
    a. Piove tanto che fa paura

Vari elementi fungono da antecedente e caratterizzano la consecutiva stessa: avverbi che modificano un aggettivo (*tanto, talmente, così*) in posizione predicativa o dopo il nome, avverbi che modificano un verbo (*tanto, talmente, troppo, abbastanza*), quantificatori che modificano un SN (*tale, tanto*, dove quest'ultimo può solo precedere il SN).


## Dichiarative

Le dichiarative (dette anche "esplicative") sono subordinate che precisano il senso di un elemento della reggente (dimostrativo o nome).

Nella forma esplicita sono introdotte da "che" e presentano una concordanza all'indicativo o al congiuntivo:

(@)
    a. Penso questo: che tu sia stata ingenerosa con Mario
    a. Ho la sensazione che Luigi se ne sia già andato

Nella forma implicita è introdotta dai due punti o da "di" e presentano il verbo all'infinito:

(@)
    a. Questo sarebbe giusto: aiutare i più sfortunati
    a. Di una cosa mi pento, di non averla richiamata 


Quando la dichiarativa è una coordinata viene introdotta da elementi quali *cioè, ovvero, in altre parole, ecc.*:

(@)
    a. Stacco dal lavoro, ovvero vado a prendere una birra
    a. Vado in campagna, cioè vado a rilassarmi



## Eccettuative

Sono subordinate che descrivono un'eccezione al verificarsi dell'evento della reggente.

Le eccettuative esplicite sono introdotte da *che, salvo che, tranne che, fuorché, a meno che*, e spesso presentano l'aggiunta della negazione pleonastica: 

(@) Non sarà un festival politico, a meno che non accada qualcosa a mia insaputa (C. Baglioni, in *Repubblica*, 04/02/2019)

Se di forma implicita, il soggetto della subordinata e quello della reggente sono coreferenti:

(@) Io accetterò tutto tranne che farmi sfruttare



## Esclusive

Le esclusive sono subordinate che esprimono un fatto escluso dalla proposizione reggente, ovvero l'evento descritto nella reggente si verifica con l'esclusione di quanto espresso nella subordinata:

(@) Non si allontani da Vigata senza avvertirci (A. Camilleri, *Il campo del vasaio*) 

Nella forma esplicita presentano spesso il congiuntivo, e nella costruzione implicita i soggetti sono coreferenti:

(@)
    a. Mi sono trovato abbonato al servizio senza che lo sapessi
    a. Mi sono trovato abbonato al servizio senza saperlo



## Finali

La proposizione finale codifica lo scopo dell'azione espressa nella reggente. La subordinata è introdotta da congiunzioni (*affinché, perché, ecc.*), locuzioni (*in modo che, ecc.*), con il congiuntivo:

(@) Ogni venerdì l'attivista svedese 16enne Greta Thunberg salta la scuola per manifestare affinché i potenti della Terra lottino per il clima (P. Rodari, in *Repubblica*, 15/03/2019)

Nelle costruzioni implicite il soggetto della reggente e quello della subordinata sono coreferenti e la subordinata viene introdotta da *per* o altre locuzioni (*al fine di, in modo da, ecc.*):

(@) Gli studenti stanno studiando molto per superare l'esame di sintassi



## Limitative

La proposizione limitativa è una subordinata che limita la validità dell'evento della reggente. Si può usare l'indicativo e anche il congiuntivo nella forma esplicita, mentre quella implicita presenta di solito l'infinito:

(@)
    a. Per quanto ne so, Marina non è fidanzata
    a. Per quel che riguarda Marina, non credo sia fidanzata
    a. A parlare sei bravo, ma non a scrivere


## Modali

Le proposizioni modali precisano il *modo* in cui si verifica l'evento della reggente. Le modali esplicite possono essere inserite nella categoria delle comparative, prendendo il nome di *comparative di analogia*, diversamente dalle *comparative di grado* che abbiamo chiamato semplicemente "comparative". 

Nella forma esplicita sono introdotte da *come, quasi, neanche* o da locuzioni dal significato simile (*nel modo che, nel modo in cui*), ed esprimono la maniera in cui si svolge l'evento della reggente in rapporto con il processo descritto nella subordinata:

(@)
    a. Ho cucinato il riso come mi hai insegnato
    a. Mario svolse l'esercizio nel modo in cui gli era stato insegnato

La forma implicita è possibile solamente se i soggetti della reggente e della subordinata si riferiscono alla stessa entità (*coreferenti*). Si alternano il gerundio e l'infinito preposizionale -- preceduto ovvero da *a* o da *con*:

(@)
    a. Con lo stare sempre solo, si rende antipatico a tutti
    a. Mario passa le serate a leggere romanzi
    a. La nonna li rimproverò sgridandoli furiosamente


## Strumentali

Così come le modali precisano il *modo* del verificarsi dell'evento descritto nella reggente, le strumentali sono subordinate che indicano il *mezzo* con il quale esso si compie.
Nella maggior parte dei casi, la proposizione strumentale appare in forma implicita, con il verbo al gerundio oppure con l'infinito preceduto dall'articolo e introdotto da *con* o da locuzioni quali *a forza di, a furia di*:

(@)
    a. Ci teniamo informati sulle ultime notizie leggendo i giornali
    a. A forza di piangere, quella bambina riesce sempre a ottenere l'attenzione di tutti

Raramente troviamo la proposizione strumentale in forma esplicita, e non sempre risulta agevole distinguerla nettamente dalla costruzione condizionale:

(@)
    a. Rischi di rovinare il legno piallandolo controvena
    a. Rischi di rovinare il legno se lo pialli controvena

A volte si può essere in dubbio sul distinguere se la frase può essere una strumentale o una modale. In questo caso, si può fare riferimento al fatto che la modale risponde alla domanda "in quale modo?", mentre la strumentale "con quale mezzo?":

(@)
    a. Patrizia è guarita prendendo gli antibiotici (con quale mezzo?)
    a. Mi è corso incontro correndo (in che modo?)



## Temporali

La subordinata temporale indica la circostanza di tempo in cui si verifica l'evento descritto nella reggente. 

Le temporali possono essere di modo finito all'indicativo e al congiuntivo per esprimere l'ipoteticità (possibile o impossibile) e di modo infinito:

(@)
    a. Quando vado al lavoro passo per Náměstí Republiky
    a. Appena decidesse di partire, dovresti subito seguirlo

(@) Mi fermo sempre a Náměstí Republiky prima di andare al lavoro


Nella forma esplicita, le temporali godono di un ricco repertorio di introduttori, che permettono di codificare molti rapporti temporali. Tra loro possiamod distinguere congiunzioni semplici quali *che, quando, mentre*, modificate da avverbi o preposizioni (*prima/dopo che, fino a quando/che*), locuzioni (*visto che*).
Le temporali possono esprimere contemporaneità, anteriorità o posteriorità rispetto alla reggente, e determinarne la qualità (durativa o non durativa):


(@) *quando* determina una stessa cornice temporale tra gli eventi, siano essi effettivamente simultanei o meno:  
    a. Stavo per prendere il treno, quando mi accorsi di non avere il portafoglio
    a. Quando la bambina piangeva, Luisa la sgridava
    a. Quando ci si innamora, si sentono le farfalle nello stomaco

(@) *mentre*  introduce un rapporto di simultaneità, codificando un valore durativo della subordinata. La reggente può avere valore durativo (a), puntuale (b), iterativo (c):  
    a. Mentre dormivo, mio fratello lavorava
    a. Mentre dormivo, squillò il telefono
    a. Mentre dormivo, il pendolo rintoccava ogni mezz'ora 

(@) *finché, fintantoché, fino a che* indicano il termine dell'evento. Se la fine dell'evento della reggente coincide con quello della subordinata, viene detto *coestensiva*. Le proposizioni non coestensive presentano spesso la negazione pleonastica:  
    a. Fui felice finché fummo sposati
    a. Fui felice finché (non) ci separammo

(@) *dacché, da quando* esprimono il valore incoativo dell'evento, ovvero l'inizio. Possono essere coestensivi o meno:  
    Dacché mi sono divorziato sono felice

(@) *appena, dopo* indicano la posteriorità dell'evento --immediata quella di appena:  
    a. Appena ebbe terminato il lavoro, corse a bere un bicchiere con gli amici
    a. Dopo che la partita terminò, la squadra di casa venne titolata dello scudetto

(@) *prima che* codifica la relazione di anteriorità:  
    a. Prima che il gallo canti, mi rinnegherai tre volte 
    a. Domani mi sveglierò prima che tu rientri dalla discoteca

Quelle implicite presentano un numero minore di introduttori e una più stretta gamma di relazioni temporali:

(@) Infinito:
    a. introdotto da "a" o "in" esprime simultaneità  
    A vederla, mi si rimescola il sangue
    a. introdotto da "prima di" esprime anteriorità  
    Prima di cenare mi lavo sempre le mani
    a. introdotto da "dopo" per la posteriorità  
    Dopo aver cenato, mi fumo una sigaretta

(@) Participio passato esprime la posteriorità  
    Tornata a casa, si mise a letto

(@) Gerundio:
    a. presente per esprimere simultaneità  
    Tornando a casa, si fermò dal tabaccaio
    a. passato, per la posteriorità  
    Essendo tornata a casa, si ricordò della lettera

Non vi è limite teorico all'incassamento di proposizioni temporali:

(@) Quando vivevo a Roma ero solito ammirare il Pantheon mentre pranzavo, finché non mi sono trasferito al mare