# Proposizioni non argomentali

Se come abbiamo mostrato finora le subordinate possono essere utilizzate in funzione di argomenti sintattici della reggente --sia come soggetto che come oggetto diretto e indiretto-- un'importante categoria delle subordinate è rappresentata da quelle proposizioni che non hanno valore argomentale. Così queste frasi si presentano come dei *circostanziali*, che presentano ognuno un tipico modo di codificare il rapporto delle informazioni tra reggente e secondarie, instaurando ora un rapporto di dipendenza e causalità, ora uno di negazione, comparazione, e così via. 

Come già visto per le argomentali, rimane tipica di tutte le subordinate la possibilità di essere resa in maniera *esplicita* --con un verbo di modo finito-- o *implicita*. Anche qui, come già visto nelle argomentali, potrebbero esserci delle differenze tra le forme delle preposizioni nel modo in cui possono accettare tale variazione e sulle preposizioni e i costrutti utilizzati. Vedremo nel dettaglio la maggior parte delle subordinate non argomentali qui di seguito. Spesso è possibile trovare nei manuali la dicitura di proposizioni *avverbiali* per riferirci a questo tipo di subordinazione: avverbiali e non argomentali valgono sostanzialmente per significare la stessa cosa ma qui si preferisce la distinzione tra argomento/non argomento per esplicitare la loro funzione nei riguardi del nucleo sintattico della reggente.

Sebbene ciascuna di queste classi di subordinate sia introdotta da un certo numero di elementi lessicali tipici, spesso alcune subordinate usano tali elementi in maniera non strettamente aderente al significato originario, dando luogo a costrutti più o meno figurati.

## Proposizioni avversative



## Proposizioni causali

