--- 
title: "Sintassi Italiana 2"
subtitle: "Dispense per gli studenti del corso KRI/SYNT2"
author: "Marco Petolicchio"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: scrbook
lot: yes
lof: yes
classoption: [a4paper,twoside,11pt,chapterprefix=false, bibliography=totocnumbered,listof=flat]
bibliography: [bibliography.bib]
biblio-style: apa
link-citations: yes
github-repo: p-marco.github.io/sintassiIta2
description: "sintassiIta2"
always_allow_html: yes
---

# Introduzione {-}

Questa dispensa nasce come materiale di studio per l'esame di Sintassi Italiana 2 per gli studenti triennali dell'Università Palacky di Olomouc, pensata in maniera specifica per studenti non madrelingua. Si fa riferimento a nozioni *tradizionali* della linguistica e degli studi sintattici rimandando, laddove si è ritenuto più pertinente, a degli studi più recenti in maniera da poter stimolare ulteriormente lo studente.  

Le abbreviazioni morfologiche e lo stile delle glosse interlineari aderiscono rispettivamente agli standard *de facto* delle annotazioni di linguistica comparativa [@boeckxListOfAbbreviations, [consultabile online](http://www.oxfordhandbooks.com/view/10.1093/oxfordhb/9780199549368.001.0001/oxfordhb-9780199549368)] e dello stile delle glosse *di Lipsia* [@leipzigGlossingRules].

Nel testo si segue l'uso standard di definire i vari gradi di accettabilità di una frase attraverso le seguenti marche tipografiche:

* ( ) Grammaticale
* (*) Agrammaticale
* (?) Dubbia grammaticalità
* (#) Grammaticale dal punto di vista sintattico ma interpretazione semantica non coerente

Per qualsiasi informazione o suggerimento è possibile scrivere direttamente all'autore all'indirizzo `marco.petolicchio01@upol.cz` oppure aprire un issue direttamente sulla pagina del repository su [Github](http://github.com/p-marco/sintassiIta2).

Quest'opera è rilasciata con licenza Creative Commons BY 4.0. Il codice sorgente è disponibile all'indirizzo `http://github.com/p-marco/sintassiIta2` e le versioni del progetto sono rilasciate in DOI attraverso la piattaforma Zenodo (DOI:10.5281/zenodo.2355707).



